export const INITIAL_ART_STYLES = [
  {
    id: "preset_realistic_cinematic",
    name: "电影写实",
    nameEn: "Cinematic Realistic",
    description: "电影级写实摄影风格，真实光影，细腻质感，电影级景深效果",
    prompt: "Cinematic photorealistic style",
    previewImage: null,
    tags: ["写实", "电影", "摄影"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_anime_modern",
    name: "新海诚风格",
    nameEn: "Makoto Shinkai Style",
    description: "新海诚动画美学，超精细背景绘制，真实云层与天空，镜头光晕与逆光，都市风景的诗意化呈现",
    prompt: "Makoto Shinkai anime style",
    previewImage: null,
    tags: ["新海诚", "光影", "唯美", "都市"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_korean_drama",
    name: "韩剧风格",
    nameEn: "K-Drama Style",
    description: "韩剧摄影风格，柔和光线，时尚感，精致调色",
    prompt: "Korean drama cinematography style",
    previewImage: null,
    tags: ["韩剧", "摄影", "柔光"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_pixar_3d",
    name: "3D动画",
    nameEn: "3D Animation",
    description: "皮克斯风格3D动画画风，圆润造型，生动表情，专业渲染",
    prompt: "Pixar 3D animation style",
    previewImage: null,
    tags: ["3D", "动画", "CGI"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_ghibli",
    name: "吉卜力手绘",
    nameEn: "Studio Ghibli",
    description: "吉卜力工作室手绘风格，温暖色调，细腻背景，水彩质感",
    prompt: "Studio Ghibli style",
    previewImage: null,
    tags: ["吉卜力", "手绘", "水彩"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_retro_anime",
    name: "复古动漫",
    nameEn: "Retro Anime",
    description: "80-90年代复古动漫画风，怀旧色调，经典赛璐珞，胶片颗粒",
    prompt: "1980s-90s retro anime style",
    previewImage: null,
    tags: ["复古", "80年代", "怀旧"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_tv_anime",
    name: "TV动画标准",
    nameEn: "TV Anime Standard",
    description: "标准TV动画风格，清晰的线条，稳定的作画质量，平衡的色彩，适合批量制作和日常题材",
    prompt: "Standard TV anime style",
    previewImage: null,
    tags: ["TV动画", "标准", "日常", "稳定"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_dream_reality_blur",
    name: "梦境交错",
    nameEn: "Dream Reality Blur",
    description: "今敏风格意识流动画，现实与梦境无缝切换，都市迷幻氛围，探索潜意识的边界",
    prompt: "Satoshi Kon style",
    previewImage: null,
    tags: ["今敏", "意识流", "梦境", "都市"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
];

