export const INITIAL_ART_STYLES = [
  {
    id: "preset_realistic_cinematic",
    name: "电影写实",
    nameEn: "Cinematic Realistic",
    description: "电影级写实摄影风格，真实光影，细腻质感，电影级景深效果",
    prompt: "Cinematic realistic photography with dramatic lighting and film grain. Photorealistic with depth of field.",
    previewImage: null,
    tags: ["写实", "电影", "摄影"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_anime_modern",
    name: "光影动漫",
    nameEn: "Cinematic Anime",
    description: "超写实背景，细腻光影效果，唯美天空，强烈的光线与色彩表现",
    prompt: "Anime style with photorealistic backgrounds and dramatic lighting. Detailed sky with beautiful light rays and lens flare effects.",
    previewImage: null,
    tags: ["动漫", "光影", "写实"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_korean_drama",
    name: "韩剧风格",
    nameEn: "K-Drama Style",
    description: "韩剧摄影风格，柔和光线，时尚感，精致调色",
    prompt: "Korean drama cinematography with soft romantic lighting. Beautiful color grading with fashionable aesthetic.",
    previewImage: null,
    tags: ["韩剧", "摄影", "柔光"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_pixar_3d",
    name: "3D动画",
    nameEn: "3D Animation",
    description: "皮克斯风格3D动画画风，圆润造型，生动表情，专业渲染",
    prompt: "Pixar-style 3D animation with expressive characters and vibrant colors. Smooth professional CGI rendering.",
    previewImage: null,
    tags: ["3D", "动画", "CGI"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_ghibli",
    name: "吉卜力手绘",
    nameEn: "Studio Ghibli",
    description: "吉卜力工作室手绘风格，温暖色调，细腻背景，水彩质感",
    prompt: "Studio Ghibli hand-drawn style with warm atmosphere. Detailed painterly backgrounds with soft watercolor quality.",
    previewImage: null,
    tags: ["吉卜力", "手绘", "水彩"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_retro_anime",
    name: "复古动漫",
    nameEn: "Retro Anime",
    description: "80-90年代复古动漫画风，怀旧色调，经典赛璐珞，胶片颗粒",
    prompt: "1980s-1990s retro anime style with classic cel animation. Nostalgic vintage aesthetic with grainy texture.",
    previewImage: null,
    tags: ["复古", "80年代", "怀旧"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_comic_western",
    name: "美式漫画",
    nameEn: "Western Comic",
    description: "美式漫画画风，粗犷线条，色彩鲜明，动态构图",
    prompt: "Western comic book art style with bold ink lines and vibrant colors. Dynamic composition with strong outlines.",
    previewImage: null,
    tags: ["漫画", "美式", "线条"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_thick_paint",
    name: "厚涂插画",
    nameEn: "Thick Paint Illustration",
    description: "数字厚涂绘画风格，厚重笔触，丰富色彩层次，油画质感",
    prompt: "Digital painting with thick brushstrokes and rich color layers. Oil painting texture with visible brush marks.",
    previewImage: null,
    tags: ["厚涂", "插画", "绘画"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
  {
    id: "preset_shounen_manga",
    name: "少年漫画",
    nameEn: "Shounen Manga",
    description: "日本少年漫画风格，硬朗线条，动态分镜，速度线与爆发效果，充满力量感",
    prompt: "Japanese shounen manga style with bold dynamic linework and action lines. High-energy composition with motion blur effects and dramatic impact frames.",
    previewImage: null,
    tags: ["少年漫画", "动作", "热血"],
    userId: null,
    isPublic: false,
    usageCount: 0,
  },
];

